export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    signup: "/auth/signup",
    refresh: "/auth/refresh",
    username: "/auth/username",
    acceptInvite: "/auth/accept-invite",
  },
  profile: "/users/me",
  files: {
    upload: "/public/upload/files",
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
  users: { getAll: "/users" },
  products: { getAll: "/products" },
  orders: { getAll: "/orders" },
  reports: { getAll: "/reports" },
  inventories: { getAll: "/inventories" },
  categories: { getAll: "/categories" },
  subCategories: { getAll: "/sub-categories" },
  queries: { getAll: "/queries" },
  productInquiries: { getAll: "/product-inquiries" },
  blogs: { getAll: "/blogs" },
  // RC modules
  enquiries: { getAll: "/enquiries" },
  articles: { getAll: "/articles" },
  caseStudies: { getAll: "/case-studies" },
  advisers: { getAll: "/advisers" },
  jobs: { getAll: "/jobs" },
  industries: { getAll: "/industries" },
  schemes: { getAll: "/schemes" },
  services: { getAll: "/services" } 
};
