import routes from "@/lib/data/page-routes.json";

// Content identity (e.g. "D060") -> public path without locale
// ("/services/change-in-land-use-clu"). Generated by scripts/build-page-routes.mjs.
export const pageRoutes = routes;

const byPath = new Map(Object.entries(routes).filter(([id]) => id !== "D064").map(([id, path]) => [path, id]));

export const pathFor = (id, locale) => (id in routes ? `/${locale}${routes[id]}` : null);

// "/schemes/pmegp-kvic-scheme" -> "D001"
export const idForPath = (path) => byPath.get(path) ?? null;

// Content links are written as /{locale}/p/{ID}; they become slug URLs when
// rendered. Unknown identities are left untouched.
const INTERNAL = /href="\/(en|hi)\/p\/([^"#?]+)([^"]*)"/g;
export function rewriteContentLinks(html) {
  if (!html) return html;
  return html.replace(INTERNAL, (match, locale, id, rest) => {
    const path = pathFor(id, locale);
    return path ? `href="${path}${rest}"` : match;
  });
}

// Converts a single /{locale}/p/{ID} href (or returns it unchanged).
export function toSlugHref(href) {
  const m = href?.match(/^\/(en|hi)\/p\/([^"#?]+)(.*)$/);
  if (!m) return href;
  return (pathFor(m[2], m[1]) ?? href) + m[3];
}
